name: Test Godot Install

on:
  push:
    branches: [ main ]

jobs:
  test-godot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.6.0 # https://www.nuget.org/packages/GodotSharp#versions-body-tab
          use-dotnet: false

      - name: Install SCons
        run: sudo apt-get update && sudo apt-get install -y scons

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build GDExtension for Web
        run: |
          mkdir -p project/bin
          scons platform=web target=template_debug

      - name: Check build
        run: ls project/bin
          
      - name: Test godot engine
        run: godot --headless --editor --quit

      - name: Show export presets
        run: cat project/export_presets.cfg
        
      - name: Export Web build
        run: |
          mkdir -p build/web
          godot --headless --path project --export-debug "Web" build/web/index.html
        
      - name: Show build output
        run: ls build/web